using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Parking.Infrastructure.Persistence;

#nullable disable

namespace Parking.Infrastructure.Migrations
{
    /// <summary>
    /// Расширение схемы Parking/GiRPlus по утверждённой проектной схеме.
    ///
    /// Важно:
    /// - passages и parking_sessions не перестраиваются;
    /// - legacy-поля contracts / employees.role / watchlist.type физически сохраняются,
    ///   чтобы миграция была безопасной и обратимой;
    /// - новые финансовые поля contract_places заполняются из contracts;
    /// - PaymentItems не создаются.
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709130000_ExpandParkingSchema")]
    public partial class ExpandParkingSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
            -- ============================================================
            -- 1. Роли сотрудников
            -- ============================================================
            CREATE TABLE roles (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(32) NOT NULL,
                name varchar(64) NOT NULL,
                is_active boolean NOT NULL DEFAULT TRUE
            );

            CREATE UNIQUE INDEX ux_roles_code ON roles(code);

            INSERT INTO roles(code, name, is_active)
            VALUES
                ('ADMIN', 'Администратор', TRUE),
                ('OPERATOR', 'Оператор', TRUE),
                ('MANAGER', 'Менеджер', TRUE)
            ON CONFLICT (code) DO NOTHING;

            INSERT INTO roles(code, name, is_active)
            SELECT DISTINCT
                LEFT(UPPER(REPLACE(TRIM(role), ' ', '_')), 32),
                LEFT(TRIM(role), 64),
                TRUE
            FROM employees
            WHERE role IS NOT NULL AND TRIM(role) <> ''
            ON CONFLICT (code) DO NOTHING;

            ALTER TABLE employees
                ADD COLUMN residential_address varchar(512) NULL,
                ADD COLUMN jpeg_path varchar(512) NOT NULL DEFAULT '',
                ADD COLUMN role_id bigint NULL,
                ADD COLUMN login varchar(64) NULL,
                ADD COLUMN password_hash varchar(255) NULL;

            UPDATE employees e
            SET role_id = r.id
            FROM roles r
            WHERE e.role IS NOT NULL
              AND r.code = LEFT(UPPER(REPLACE(TRIM(e.role), ' ', '_')), 32);

            ALTER TABLE employees
                ADD CONSTRAINT fk_employees_roles_role_id
                FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT;

            CREATE INDEX ix_employees_role ON employees(role_id);
            CREATE UNIQUE INDEX ux_employees_login
                ON employees(login)
                WHERE login IS NOT NULL;

            -- ============================================================
            -- 2. Смены
            -- ============================================================
            CREATE TABLE shifts (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                employee_id bigint NOT NULL,
                started_at timestamptz NOT NULL,
                ended_at timestamptz NULL,
                opening_cash numeric(12,2) NOT NULL DEFAULT 0,
                closing_cash numeric(12,2) NULL,
                notes text NULL,
                CONSTRAINT fk_shifts_employees_employee_id
                    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_shifts_employee_started
                ON shifts(employee_id, started_at);

            -- ============================================================
            -- 3. Owners + Telegram
            -- ============================================================
            ALTER TABLE owners
                ADD COLUMN residential_address varchar(512) NULL,
                ADD COLUMN jpeg_path varchar(512) NULL,
                ADD COLUMN telegram_chat_id bigint NULL,
                ADD COLUMN telegram_user_id bigint NULL,
                ADD COLUMN telegram_username varchar(64) NULL,
                ADD COLUMN telegram_linked_at timestamptz NULL,
                ADD COLUMN telegram_enabled boolean NOT NULL DEFAULT FALSE,
                ADD COLUMN notify_entry boolean NOT NULL DEFAULT FALSE,
                ADD COLUMN notify_exit boolean NOT NULL DEFAULT FALSE,
                ADD COLUMN notify_payment_due boolean NOT NULL DEFAULT FALSE,
                ADD COLUMN notify_debt_warning boolean NOT NULL DEFAULT FALSE;

            -- ============================================================
            -- 4. Типы мест
            -- ============================================================
            CREATE TABLE place_types (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(32) NOT NULL,
                name varchar(64) NOT NULL,
                is_active boolean NOT NULL DEFAULT TRUE,
                notes text NULL
            );

            CREATE UNIQUE INDEX ux_place_types_code ON place_types(code);

            INSERT INTO place_types(code, name, is_active)
            VALUES
                ('STANDARD', 'Стандарт', TRUE),
                ('COMFORT', 'Комфорт', TRUE),
                ('SERVICE', 'Сервис', TRUE),
                ('EV', 'Зарядка', TRUE)
            ON CONFLICT (code) DO NOTHING;

            ALTER TABLE places
                ADD COLUMN place_type_id bigint NULL;

            ALTER TABLE places
                ADD CONSTRAINT fk_places_place_types_place_type_id
                FOREIGN KEY (place_type_id) REFERENCES place_types(id) ON DELETE RESTRICT;

            CREATE INDEX ix_places_place_type ON places(place_type_id);

            -- ============================================================
            -- 5. Расширение тарифов
            -- ============================================================
            ALTER TABLE tariffs
                ADD COLUMN payment_mode varchar(16) NOT NULL DEFAULT 'PREPAID',
                ADD COLUMN grace_period_days integer NOT NULL DEFAULT 20,
                ADD COLUMN operator_message text NULL,
                ADD COLUMN stamp_text varchar(64) NULL,
                ADD COLUMN stamp_color varchar(16) NULL,
                ADD COLUMN can_pause boolean NOT NULL DEFAULT FALSE;

            -- valid_from / valid_to: date -> timestamptz.
            ALTER TABLE tariff_rates
                ALTER COLUMN valid_from TYPE timestamptz
                    USING (valid_from::timestamp AT TIME ZONE 'Europe/Chisinau');

            ALTER TABLE tariff_rates
                ALTER COLUMN valid_to TYPE timestamptz
                    USING (
                        CASE
                            WHEN valid_to IS NULL THEN NULL
                            ELSE valid_to::timestamp AT TIME ZONE 'Europe/Chisinau'
                        END
                    );

            CREATE TABLE place_type_tariffs (
                place_type_id bigint NOT NULL,
                tariff_id bigint NOT NULL,
                is_default boolean NOT NULL DEFAULT FALSE,
                CONSTRAINT pk_place_type_tariffs PRIMARY KEY (place_type_id, tariff_id),
                CONSTRAINT fk_place_type_tariffs_place_types_place_type_id
                    FOREIGN KEY (place_type_id) REFERENCES place_types(id) ON DELETE CASCADE,
                CONSTRAINT fk_place_type_tariffs_tariffs_tariff_id
                    FOREIGN KEY (tariff_id) REFERENCES tariffs(id) ON DELETE CASCADE
            );

            -- ============================================================
            -- 6. Перенос финансовой логики на contract_places
            -- ============================================================
            ALTER TABLE contract_places
                ADD COLUMN tariff_id bigint NULL,
                ADD COLUMN start_at timestamptz NULL,
                ADD COLUMN paid_until timestamptz NULL,
                ADD COLUMN pause_balance_days integer NOT NULL DEFAULT 0,
                ADD COLUMN paused_at timestamptz NULL;

            UPDATE contract_places cp
            SET
                tariff_id = c.tariff_id,
                start_at = c.start_at::timestamp AT TIME ZONE 'Europe/Chisinau',
                paid_until = CASE
                    WHEN c.paid_until IS NULL THEN NULL
                    ELSE c.paid_until::timestamp AT TIME ZONE 'Europe/Chisinau'
                END,
                pause_balance_days = c.pause_balance_days,
                paused_at = c.paused_at
            FROM contracts c
            WHERE c.id = cp.contract_id;

            ALTER TABLE contract_places
                ALTER COLUMN tariff_id SET NOT NULL,
                ALTER COLUMN start_at SET NOT NULL;

            ALTER TABLE contract_places
                ADD CONSTRAINT fk_contract_places_tariffs_tariff_id
                FOREIGN KEY (tariff_id) REFERENCES tariffs(id) ON DELETE RESTRICT;

            CREATE INDEX ix_contract_places_tariff
                ON contract_places(tariff_id);

            CREATE INDEX ix_contract_places_paid_until
                ON contract_places(paid_until);

            -- Legacy-поля contracts пока сохраняются физически.
            -- Делаем обязательные legacy-поля безопасными для новых INSERT,
            -- когда приложение уже работает через contract_places.
            ALTER TABLE contracts
                ALTER COLUMN tariff_id DROP NOT NULL,
                ALTER COLUMN start_at DROP NOT NULL,
                ALTER COLUMN pause_balance_days SET DEFAULT 0;

            -- ============================================================
            -- 7. Дополнительные услуги
            -- ============================================================
            CREATE TABLE service_types (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(32) NOT NULL,
                name varchar(128) NOT NULL,
                is_active boolean NOT NULL DEFAULT TRUE,
                notes text NULL
            );

            CREATE UNIQUE INDEX ux_service_types_code
                ON service_types(code);

            INSERT INTO service_types(code, name, is_active)
            VALUES
                ('TELEGRAM_NOTIFY', 'Telegram-уведомления', TRUE),
                ('TIRE_STORAGE', 'Хранение шин', TRUE)
            ON CONFLICT (code) DO NOTHING;

            CREATE TABLE contract_services (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                contract_id bigint NOT NULL,
                service_type_id bigint NOT NULL,
                tariff_id bigint NOT NULL,
                status varchar(16) NOT NULL,
                start_at timestamptz NOT NULL,
                paid_until timestamptz NULL,
                paused_at timestamptz NULL,
                notes text NULL,
                CONSTRAINT fk_contract_services_contracts_contract_id
                    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE,
                CONSTRAINT fk_contract_services_service_types_service_type_id
                    FOREIGN KEY (service_type_id) REFERENCES service_types(id) ON DELETE RESTRICT,
                CONSTRAINT fk_contract_services_tariffs_tariff_id
                    FOREIGN KEY (tariff_id) REFERENCES tariffs(id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_contract_services_contract
                ON contract_services(contract_id);

            CREATE INDEX ix_contract_services_service_type
                ON contract_services(service_type_id);

            CREATE INDEX ix_contract_services_paid_until
                ON contract_services(paid_until);

            -- ============================================================
            -- 8. Платежи
            -- ============================================================
            ALTER TABLE payments
                ADD COLUMN place_id bigint NULL,
                ADD COLUMN contract_service_id bigint NULL,
                ADD COLUMN shift_id bigint NULL;

            ALTER TABLE payments
                ALTER COLUMN covered_from TYPE timestamptz
                    USING (
                        CASE
                            WHEN covered_from IS NULL THEN NULL
                            ELSE covered_from::timestamp AT TIME ZONE 'Europe/Chisinau'
                        END
                    );

            ALTER TABLE payments
                ALTER COLUMN covered_to TYPE timestamptz
                    USING (
                        CASE
                            WHEN covered_to IS NULL THEN NULL
                            ELSE covered_to::timestamp AT TIME ZONE 'Europe/Chisinau'
                        END
                    );

            ALTER TABLE payments
                ADD CONSTRAINT fk_payments_contract_places_contract_id_place_id
                FOREIGN KEY (contract_id, place_id)
                REFERENCES contract_places(contract_id, place_id)
                ON DELETE RESTRICT;

            ALTER TABLE payments
                ADD CONSTRAINT fk_payments_contract_services_contract_service_id
                FOREIGN KEY (contract_service_id)
                REFERENCES contract_services(id)
                ON DELETE RESTRICT;

            ALTER TABLE payments
                ADD CONSTRAINT fk_payments_shifts_shift_id
                FOREIGN KEY (shift_id)
                REFERENCES shifts(id)
                ON DELETE RESTRICT;

            CREATE INDEX ix_payments_contract_place
                ON payments(contract_id, place_id);

            CREATE INDEX ix_payments_contract_service
                ON payments(contract_service_id);

            CREATE INDEX ix_payments_shift
                ON payments(shift_id);

            -- ============================================================
            -- 9. Watchlist types
            -- ============================================================
            CREATE TABLE watchlist_types (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(32) NOT NULL,
                name varchar(64) NOT NULL,
                allow_unrestricted_access boolean NOT NULL DEFAULT FALSE,
                unlimited_stay boolean NOT NULL DEFAULT FALSE,
                operator_message text NULL,
                stamp_text varchar(64) NULL,
                stamp_color varchar(16) NULL,
                is_active boolean NOT NULL DEFAULT TRUE
            );

            CREATE UNIQUE INDEX ux_watchlist_types_code
                ON watchlist_types(code);

            INSERT INTO watchlist_types(
                code, name, allow_unrestricted_access, unlimited_stay, is_active)
            VALUES
                ('VIP', 'VIP', TRUE, TRUE, TRUE),
                ('BLACKLIST', 'Чёрный список', FALSE, FALSE, TRUE),
                ('SERVICE', 'Служебный', TRUE, TRUE, TRUE),
                ('STAFF', 'Сотрудник', TRUE, TRUE, TRUE),
                ('NOTIFYONLY', 'Только уведомление', TRUE, TRUE, TRUE)
            ON CONFLICT (code) DO NOTHING;

            INSERT INTO watchlist_types(
                code, name, allow_unrestricted_access, unlimited_stay, is_active)
            SELECT DISTINCT
                LEFT(UPPER(REPLACE(TRIM(type), ' ', '_')), 32),
                LEFT(TRIM(type), 64),
                FALSE,
                FALSE,
                TRUE
            FROM watchlist
            WHERE type IS NOT NULL AND TRIM(type) <> ''
            ON CONFLICT (code) DO NOTHING;

            ALTER TABLE watchlist
                ADD COLUMN watchlist_type_id bigint NULL;

            UPDATE watchlist w
            SET watchlist_type_id = wt.id
            FROM watchlist_types wt
            WHERE wt.code = LEFT(UPPER(REPLACE(TRIM(w.type), ' ', '_')), 32);

            ALTER TABLE watchlist
                ALTER COLUMN type DROP NOT NULL;

            ALTER TABLE watchlist
                ADD CONSTRAINT fk_watchlist_watchlist_types_watchlist_type_id
                FOREIGN KEY (watchlist_type_id)
                REFERENCES watchlist_types(id)
                ON DELETE RESTRICT;

            CREATE INDEX ix_watchlist_type_id
                ON watchlist(watchlist_type_id);

            -- ============================================================
            -- 10. Уведомления
            -- ============================================================
            CREATE TABLE notifications (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                owner_id bigint NOT NULL,
                vehicle_id bigint NULL,
                passage_id bigint NULL,
                notification_type varchar(32) NOT NULL,
                message_text text NOT NULL,
                status varchar(16) NOT NULL,
                created_at timestamptz NOT NULL,
                sent_at timestamptz NULL,
                error_text text NULL,
                CONSTRAINT fk_notifications_owners_owner_id
                    FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE RESTRICT,
                CONSTRAINT fk_notifications_vehicles_vehicle_id
                    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE RESTRICT,
                CONSTRAINT fk_notifications_passages_passage_id
                    FOREIGN KEY (passage_id) REFERENCES passages(id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_notifications_owner
                ON notifications(owner_id);
            CREATE INDEX ix_notifications_status
                ON notifications(status);
            CREATE INDEX ix_notifications_created_at
                ON notifications(created_at);
            CREATE INDEX ix_notifications_passage
                ON notifications(passage_id);

            -- ============================================================
            -- 11. Камеры
            -- ============================================================
            CREATE TABLE camera_types (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code varchar(32) NOT NULL,
                name varchar(64) NOT NULL
            );

            CREATE UNIQUE INDEX ux_camera_types_code
                ON camera_types(code);

            INSERT INTO camera_types(code, name)
            VALUES
                ('LPR', 'Распознавание номеров'),
                ('MOTION', 'Детектор движения'),
                ('OVERVIEW', 'Обзорная камера')
            ON CONFLICT (code) DO NOTHING;

            CREATE TABLE cameras (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(128) NOT NULL,
                camera_type_id bigint NOT NULL,
                address varchar(255) NULL,
                location varchar(255) NULL,
                is_active boolean NOT NULL,
                notes text NULL,
                CONSTRAINT fk_cameras_camera_types_camera_type_id
                    FOREIGN KEY (camera_type_id) REFERENCES camera_types(id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_cameras_type_active
                ON cameras(camera_type_id, is_active);

            CREATE TABLE camera_zones (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                camera_id bigint NOT NULL,
                code varchar(32) NOT NULL,
                name varchar(128) NOT NULL,
                notes text NULL,
                CONSTRAINT fk_camera_zones_cameras_camera_id
                    FOREIGN KEY (camera_id) REFERENCES cameras(id) ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX ux_camera_zones_camera_code
                ON camera_zones(camera_id, code);

            CREATE TABLE camera_zone_places (
                camera_zone_id bigint NOT NULL,
                place_id bigint NOT NULL,
                CONSTRAINT pk_camera_zone_places
                    PRIMARY KEY (camera_zone_id, place_id),
                CONSTRAINT fk_camera_zone_places_camera_zones_camera_zone_id
                    FOREIGN KEY (camera_zone_id) REFERENCES camera_zones(id) ON DELETE CASCADE,
                CONSTRAINT fk_camera_zone_places_places_place_id
                    FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE
            );

            CREATE TABLE camera_events (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                camera_id bigint NOT NULL,
                camera_zone_id bigint NULL,
                event_type varchar(32) NOT NULL,
                occurred_at timestamptz NOT NULL,
                jpeg_path varchar(512) NULL,
                raw_data jsonb NULL,
                CONSTRAINT fk_camera_events_cameras_camera_id
                    FOREIGN KEY (camera_id) REFERENCES cameras(id) ON DELETE RESTRICT,
                CONSTRAINT fk_camera_events_camera_zones_camera_zone_id
                    FOREIGN KEY (camera_zone_id) REFERENCES camera_zones(id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_camera_events_camera_occurred
                ON camera_events(camera_id, occurred_at);
            CREATE INDEX ix_camera_events_zone
                ON camera_events(camera_zone_id);
            CREATE INDEX ix_camera_events_type
                ON camera_events(event_type);

            ALTER TABLE passages
                ADD COLUMN camera_id bigint NULL;

            ALTER TABLE passages
                ADD CONSTRAINT fk_passages_cameras_camera_id
                FOREIGN KEY (camera_id) REFERENCES cameras(id) ON DELETE RESTRICT;

            CREATE INDEX ix_passages_camera
                ON passages(camera_id);

            -- ============================================================
            -- 12. Шлагбаумы
            -- ============================================================
            CREATE TABLE barriers (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(128) NOT NULL,
                address varchar(255) NULL,
                controller_type varchar(32) NULL,
                is_active boolean NOT NULL,
                notes text NULL
            );

            CREATE TABLE barrier_commands (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                barrier_id bigint NOT NULL,
                command_type varchar(16) NOT NULL,
                source varchar(16) NOT NULL,
                employee_id bigint NULL,
                passage_id bigint NULL,
                requested_at timestamptz NOT NULL,
                completed_at timestamptz NULL,
                status varchar(16) NOT NULL,
                error_text text NULL,
                CONSTRAINT fk_barrier_commands_barriers_barrier_id
                    FOREIGN KEY (barrier_id) REFERENCES barriers(id) ON DELETE RESTRICT,
                CONSTRAINT fk_barrier_commands_employees_employee_id
                    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE RESTRICT,
                CONSTRAINT fk_barrier_commands_passages_passage_id
                    FOREIGN KEY (passage_id) REFERENCES passages(id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_barrier_commands_barrier
                ON barrier_commands(barrier_id);
            CREATE INDEX ix_barrier_commands_requested
                ON barrier_commands(requested_at);
            CREATE INDEX ix_barrier_commands_passage
                ON barrier_commands(passage_id);
            CREATE INDEX ix_barrier_commands_status
                ON barrier_commands(status);

            CREATE TABLE barrier_events (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                barrier_id bigint NOT NULL,
                event_type varchar(32) NOT NULL,
                occurred_at timestamptz NOT NULL,
                barrier_command_id bigint NULL,
                raw_data jsonb NULL,
                CONSTRAINT fk_barrier_events_barriers_barrier_id
                    FOREIGN KEY (barrier_id) REFERENCES barriers(id) ON DELETE RESTRICT,
                CONSTRAINT fk_barrier_events_barrier_commands_barrier_command_id
                    FOREIGN KEY (barrier_command_id) REFERENCES barrier_commands(id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_barrier_events_barrier_occurred
                ON barrier_events(barrier_id, occurred_at);
            CREATE INDEX ix_barrier_events_command
                ON barrier_events(barrier_command_id);
            CREATE INDEX ix_barrier_events_type
                ON barrier_events(event_type);

            -- ============================================================
            -- 13. Audit log
            -- ============================================================
            CREATE TABLE audit_log (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                occurred_at timestamptz NOT NULL,
                employee_id bigint NULL,
                action_code varchar(64) NOT NULL,
                entity_type varchar(64) NOT NULL,
                entity_id bigint NULL,
                old_data jsonb NULL,
                new_data jsonb NULL,
                comment text NULL,
                CONSTRAINT fk_audit_log_employees_employee_id
                    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_audit_log_occurred
                ON audit_log(occurred_at);
            CREATE INDEX ix_audit_log_employee
                ON audit_log(employee_id);
            CREATE INDEX ix_audit_log_entity
                ON audit_log(entity_type, entity_id);
            CREATE INDEX ix_audit_log_action
                ON audit_log(action_code);
            """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
            -- Удаляем в порядке, обратном зависимостям.

            DROP TABLE IF EXISTS audit_log;

            DROP TABLE IF EXISTS barrier_events;
            DROP TABLE IF EXISTS barrier_commands;
            DROP TABLE IF EXISTS barriers;

            ALTER TABLE passages
                DROP CONSTRAINT IF EXISTS fk_passages_cameras_camera_id;
            DROP INDEX IF EXISTS ix_passages_camera;
            ALTER TABLE passages
                DROP COLUMN IF EXISTS camera_id;

            DROP TABLE IF EXISTS camera_events;
            DROP TABLE IF EXISTS camera_zone_places;
            DROP TABLE IF EXISTS camera_zones;
            DROP TABLE IF EXISTS cameras;
            DROP TABLE IF EXISTS camera_types;

            DROP TABLE IF EXISTS notifications;

            ALTER TABLE watchlist
                DROP CONSTRAINT IF EXISTS fk_watchlist_watchlist_types_watchlist_type_id;
            DROP INDEX IF EXISTS ix_watchlist_type_id;
            UPDATE watchlist w
            SET type = wt.code
            FROM watchlist_types wt
            WHERE w.type IS NULL
              AND w.watchlist_type_id = wt.id;

            UPDATE watchlist
            SET type = 'NOTIFYONLY'
            WHERE type IS NULL;

            ALTER TABLE watchlist
                DROP COLUMN IF EXISTS watchlist_type_id;

            ALTER TABLE watchlist
                ALTER COLUMN type SET NOT NULL;

            DROP TABLE IF EXISTS watchlist_types;

            ALTER TABLE payments
                DROP CONSTRAINT IF EXISTS fk_payments_shifts_shift_id;
            ALTER TABLE payments
                DROP CONSTRAINT IF EXISTS fk_payments_contract_services_contract_service_id;
            ALTER TABLE payments
                DROP CONSTRAINT IF EXISTS fk_payments_contract_places_contract_id_place_id;

            DROP INDEX IF EXISTS ix_payments_shift;
            DROP INDEX IF EXISTS ix_payments_contract_service;
            DROP INDEX IF EXISTS ix_payments_contract_place;

            ALTER TABLE payments
                DROP COLUMN IF EXISTS shift_id,
                DROP COLUMN IF EXISTS contract_service_id,
                DROP COLUMN IF EXISTS place_id;

            ALTER TABLE payments
                ALTER COLUMN covered_from TYPE date
                    USING (covered_from AT TIME ZONE 'Europe/Chisinau')::date;

            ALTER TABLE payments
                ALTER COLUMN covered_to TYPE date
                    USING (covered_to AT TIME ZONE 'Europe/Chisinau')::date;

            DROP TABLE IF EXISTS contract_services;
            DROP TABLE IF EXISTS service_types;

            -- Восстанавливаем legacy-значения для контрактов, созданных после Up().
            UPDATE contracts c
            SET tariff_id = COALESCE(
                    c.tariff_id,
                    (
                        SELECT cp.tariff_id
                        FROM contract_places cp
                        WHERE cp.contract_id = c.id
                        ORDER BY cp.place_id
                        LIMIT 1
                    )
                ),
                start_at = COALESCE(
                    c.start_at,
                    (
                        SELECT (cp.start_at AT TIME ZONE 'Europe/Chisinau')::date
                        FROM contract_places cp
                        WHERE cp.contract_id = c.id
                        ORDER BY cp.place_id
                        LIMIT 1
                    )
                ),
                paid_until = COALESCE(
                    c.paid_until,
                    (
                        SELECT (cp.paid_until AT TIME ZONE 'Europe/Chisinau')::date
                        FROM contract_places cp
                        WHERE cp.contract_id = c.id
                          AND cp.paid_until IS NOT NULL
                        ORDER BY cp.place_id
                        LIMIT 1
                    )
                ),
                pause_balance_days = COALESCE(
                    c.pause_balance_days,
                    (
                        SELECT cp.pause_balance_days
                        FROM contract_places cp
                        WHERE cp.contract_id = c.id
                        ORDER BY cp.place_id
                        LIMIT 1
                    ),
                    0
                ),
                paused_at = COALESCE(
                    c.paused_at,
                    (
                        SELECT cp.paused_at
                        FROM contract_places cp
                        WHERE cp.contract_id = c.id
                          AND cp.paused_at IS NOT NULL
                        ORDER BY cp.place_id
                        LIMIT 1
                    )
                )
            WHERE c.tariff_id IS NULL OR c.start_at IS NULL;

            UPDATE contracts
            SET tariff_id = (SELECT id FROM tariffs ORDER BY id LIMIT 1)
            WHERE tariff_id IS NULL;

            UPDATE contracts
            SET start_at = CURRENT_DATE
            WHERE start_at IS NULL;

            ALTER TABLE contracts
                ALTER COLUMN tariff_id SET NOT NULL,
                ALTER COLUMN start_at SET NOT NULL,
                ALTER COLUMN pause_balance_days DROP DEFAULT;

            ALTER TABLE contract_places
                DROP CONSTRAINT IF EXISTS fk_contract_places_tariffs_tariff_id;

            DROP INDEX IF EXISTS ix_contract_places_paid_until;
            DROP INDEX IF EXISTS ix_contract_places_tariff;

            ALTER TABLE contract_places
                DROP COLUMN IF EXISTS paused_at,
                DROP COLUMN IF EXISTS pause_balance_days,
                DROP COLUMN IF EXISTS paid_until,
                DROP COLUMN IF EXISTS start_at,
                DROP COLUMN IF EXISTS tariff_id;

            DROP TABLE IF EXISTS place_type_tariffs;

            ALTER TABLE tariff_rates
                ALTER COLUMN valid_from TYPE date
                    USING (valid_from AT TIME ZONE 'Europe/Chisinau')::date;

            ALTER TABLE tariff_rates
                ALTER COLUMN valid_to TYPE date
                    USING (valid_to AT TIME ZONE 'Europe/Chisinau')::date;

            ALTER TABLE tariffs
                DROP COLUMN IF EXISTS can_pause,
                DROP COLUMN IF EXISTS stamp_color,
                DROP COLUMN IF EXISTS stamp_text,
                DROP COLUMN IF EXISTS operator_message,
                DROP COLUMN IF EXISTS grace_period_days,
                DROP COLUMN IF EXISTS payment_mode;

            ALTER TABLE places
                DROP CONSTRAINT IF EXISTS fk_places_place_types_place_type_id;
            DROP INDEX IF EXISTS ix_places_place_type;
            ALTER TABLE places
                DROP COLUMN IF EXISTS place_type_id;
            DROP TABLE IF EXISTS place_types;

            ALTER TABLE owners
                DROP COLUMN IF EXISTS notify_debt_warning,
                DROP COLUMN IF EXISTS notify_payment_due,
                DROP COLUMN IF EXISTS notify_exit,
                DROP COLUMN IF EXISTS notify_entry,
                DROP COLUMN IF EXISTS telegram_enabled,
                DROP COLUMN IF EXISTS telegram_linked_at,
                DROP COLUMN IF EXISTS telegram_username,
                DROP COLUMN IF EXISTS telegram_user_id,
                DROP COLUMN IF EXISTS telegram_chat_id,
                DROP COLUMN IF EXISTS jpeg_path,
                DROP COLUMN IF EXISTS residential_address;

            ALTER TABLE employees
                DROP CONSTRAINT IF EXISTS fk_employees_roles_role_id;
            DROP INDEX IF EXISTS ux_employees_login;
            DROP INDEX IF EXISTS ix_employees_role;

            ALTER TABLE employees
                DROP COLUMN IF EXISTS password_hash,
                DROP COLUMN IF EXISTS login,
                DROP COLUMN IF EXISTS role_id,
                DROP COLUMN IF EXISTS jpeg_path,
                DROP COLUMN IF EXISTS residential_address;

            DROP TABLE IF EXISTS shifts;
            DROP TABLE IF EXISTS roles;
            """);
        }
    }
}
