// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parking.Infrastructure.Persistence;

#nullable disable

namespace Parking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212145023_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractPlaceRow", b =>
                {
                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlaceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LinkedContractId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LinkedSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("ContractId", "PlaceId");

                    b.HasIndex("LinkedContractId")
                        .HasDatabaseName("ix_contract_places_linked");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_contract_places_place");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_contract_places_status");

                    b.ToTable("contract_places", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerOwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PaidUntil")
                        .HasColumnType("date");

                    b.Property<int>("PauseBalanceDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOwnerId")
                        .HasDatabaseName("ix_contracts_owner");

                    b.HasIndex("PaidUntil")
                        .HasDatabaseName("ix_contracts_paiduntil");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_contracts_status");

                    b.HasIndex("TariffId");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractVehicleRow", b =>
                {
                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("ContractId", "VehicleId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_contract_vehicles_vehicle");

                    b.ToTable("contract_vehicles", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.EmployeeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_employees_phone");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.OwnerRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_owners_phone");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ParkingSessionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlateNorm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PlateNorm", "ClosedAt");

                    b.ToTable("parking_sessions", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PassageRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short?>("Confidence")
                        .HasColumnType("smallint")
                        .HasColumnName("confidence");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint");

                    b.Property<string>("JpegPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlateNorm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PlateRaw")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("PlateNorm");

                    b.ToTable("passages", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PaymentRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("CoveredFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CoveredTo")
                        .HasColumnType("date");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("EvidenceRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiptNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_payments_contract");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PaidAt")
                        .HasDatabaseName("ix_payments_paidat");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PlaceRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Block")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PlaceNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_places_placeno");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.TariffRateRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TariffId", "ValidFrom", "ValidTo")
                        .HasDatabaseName("ix_tariff_rates_period");

                    b.ToTable("tariff_rates", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.TariffRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BillingModel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BillingModel")
                        .HasDatabaseName("ix_tariffs_billingmodel");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.VehicleOwnerRow", b =>
                {
                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPayer")
                        .HasColumnType("boolean");

                    b.HasKey("VehicleId", "OwnerId");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vehicle_owners_owner");

                    b.ToTable("vehicle_owners", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.VehicleRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PlateNorm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PlateRaw")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PlateNorm")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_platenorm");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.WatchlistItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<bool>("NotifyOnIn")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnOut")
                        .HasColumnType("boolean");

                    b.Property<string>("PlateNorm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("PlateNorm")
                        .HasDatabaseName("ix_watchlist_plate");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_watchlist_type");

                    b.ToTable("watchlist", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractPlaceRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "Contract")
                        .WithMany("ContractPlaces")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "LinkedContract")
                        .WithMany("LinkedPlaces")
                        .HasForeignKey("LinkedContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.PlaceRow", "Place")
                        .WithMany("ContractPlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("LinkedContract");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.OwnerRow", "CustomerOwner")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.TariffRow", "Tariff")
                        .WithMany("Contracts")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerOwner");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractVehicleRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "Contract")
                        .WithMany("ContractVehicles")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.VehicleRow", "Vehicle")
                        .WithMany("ContractVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PaymentRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.EmployeeRow", "Employee")
                        .WithMany("Payments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contract");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.TariffRateRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.TariffRow", "Tariff")
                        .WithMany("Rates")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.VehicleOwnerRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.OwnerRow", "Owner")
                        .WithMany("VehicleOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.VehicleRow", "Vehicle")
                        .WithMany("VehicleOwners")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractRow", b =>
                {
                    b.Navigation("ContractPlaces");

                    b.Navigation("ContractVehicles");

                    b.Navigation("LinkedPlaces");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.EmployeeRow", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.OwnerRow", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("VehicleOwners");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PlaceRow", b =>
                {
                    b.Navigation("ContractPlaces");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.TariffRow", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.VehicleRow", b =>
                {
                    b.Navigation("ContractVehicles");

                    b.Navigation("VehicleOwners");
                });
#pragma warning restore 612, 618
        }
    }
}
