// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Parking.Infrastructure.Persistence;

#nullable disable

namespace Parking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.AuditLogRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action_code");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("OldData")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_data");

                    b.Property<string>("NewData")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_data");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_audit_log_employee");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity");

                    b.HasIndex("ActionCode")
                        .HasDatabaseName("ix_audit_log_action");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.BarrierCommandRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarrierId")
                        .HasColumnType("bigint")
                        .HasColumnName("barrier_id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("command_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<long?>("PassageId")
                        .HasColumnType("bigint")
                        .HasColumnName("passage_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("ErrorText")
                        .HasColumnType("text")
                        .HasColumnName("error_text");

                    b.HasKey("Id");

                    b.HasIndex("BarrierId")
                        .HasDatabaseName("ix_barrier_commands_barrier");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("ix_barrier_commands_requested");

                    b.HasIndex("PassageId")
                        .HasDatabaseName("ix_barrier_commands_passage");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_barrier_commands_status");

                    b.ToTable("barrier_commands", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.BarrierEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BarrierId")
                        .HasColumnType("bigint")
                        .HasColumnName("barrier_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long?>("BarrierCommandId")
                        .HasColumnType("bigint")
                        .HasColumnName("barrier_command_id");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.HasKey("Id");

                    b.HasIndex("BarrierId", "OccurredAt")
                        .HasDatabaseName("ix_barrier_events_barrier_occurred");

                    b.HasIndex("BarrierCommandId")
                        .HasDatabaseName("ix_barrier_events_command");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_barrier_events_type");

                    b.ToTable("barrier_events", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.BarrierRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("ControllerType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("controller_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.ToTable("barriers", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CameraId")
                        .HasColumnType("bigint")
                        .HasColumnName("camera_id");

                    b.Property<long?>("CameraZoneId")
                        .HasColumnType("bigint")
                        .HasColumnName("camera_zone_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("JpegPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("jpeg_path");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.HasKey("Id");

                    b.HasIndex("CameraId", "OccurredAt")
                        .HasDatabaseName("ix_camera_events_camera_occurred");

                    b.HasIndex("CameraZoneId")
                        .HasDatabaseName("ix_camera_events_zone");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_camera_events_type");

                    b.ToTable("camera_events", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("CameraTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("camera_type_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("CameraTypeId", "IsActive")
                        .HasDatabaseName("ix_cameras_type_active");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraTypeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_camera_types_code");

                    b.ToTable("camera_types", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraZonePlaceRow", b =>
                {
                    b.Property<long>("CameraZoneId")
                        .HasColumnType("bigint")
                        .HasColumnName("camera_zone_id");

                    b.Property<long>("PlaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("place_id");

                    b.HasKey("CameraZoneId", "PlaceId");

                    b.ToTable("camera_zone_places", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraZoneRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CameraId")
                        .HasColumnType("bigint")
                        .HasColumnName("camera_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("CameraId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_camera_zones_camera_code");

                    b.ToTable("camera_zones", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractPlaceRow", b =>
                {
                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<long>("PlaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("place_id");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTimeOffset?>("PaidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_until");

                    b.Property<int>("PauseBalanceDays")
                        .HasDefaultValue(0)
                        .HasColumnType("integer")
                        .HasColumnName("pause_balance_days");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<long?>("LinkedContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("linked_contract_id");

                    b.Property<DateTimeOffset?>("LinkedSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_since");

                    b.HasKey("ContractId", "PlaceId");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_contract_places_place");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_contract_places_status");

                    b.HasIndex("LinkedContractId")
                        .HasDatabaseName("ix_contract_places_linked");

                    b.HasIndex("TariffId")
                        .HasDatabaseName("ix_contract_places_tariff");

                    b.HasIndex("PaidUntil")
                        .HasDatabaseName("ix_contract_places_paid_until");

                    b.ToTable("contract_places", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerOwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOwnerId")
                        .HasDatabaseName("ix_contracts_owner");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_contracts_status");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractServiceRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_type_id");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTimeOffset?>("PaidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_until");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_services_contract");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_contract_services_service_type");

                    b.HasIndex("PaidUntil")
                        .HasDatabaseName("ix_contract_services_paid_until");

                    b.ToTable("contract_services", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractVehicleRow", b =>
                {
                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.HasKey("ContractId", "VehicleId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_contract_vehicles_vehicle");

                    b.ToTable("contract_vehicles", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.EmployeeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("surname");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone");

                    b.Property<string>("ResidentialAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("residential_address");

                    b.Property<string>("JpegPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasDefaultValue("")
                        .HasColumnType("character varying(512)")
                        .HasColumnName("jpeg_path");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<string>("Login")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_employees_phone");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_employees_role");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasFilter("login IS NOT NULL")
                        .HasDatabaseName("ux_employees_login");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.NotificationRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.Property<long?>("PassageId")
                        .HasColumnType("bigint")
                        .HasColumnName("passage_id");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("notification_type");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("ErrorText")
                        .HasColumnType("text")
                        .HasColumnName("error_text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_notifications_owner");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_notifications_status");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("PassageId")
                        .HasDatabaseName("ix_notifications_passage");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.OwnerRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("surname");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone");

                    b.Property<string>("ResidentialAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("residential_address");

                    b.Property<string>("JpegPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("jpeg_path");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("telegram_username");

                    b.Property<DateTimeOffset?>("TelegramLinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("telegram_linked_at");

                    b.Property<bool>("TelegramEnabled")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("telegram_enabled");

                    b.Property<bool>("NotifyEntry")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("notify_entry");

                    b.Property<bool>("NotifyExit")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("notify_exit");

                    b.Property<bool>("NotifyPaymentDue")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("notify_payment_due");

                    b.Property<bool>("NotifyDebtWarning")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("notify_debt_warning");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_owners_phone");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ParkingSessionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PlateNorm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate_norm");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.HasKey("Id");

                    b.HasIndex("PlateNorm", "ClosedAt");

                    b.ToTable("parking_sessions", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PassageRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PlateRaw")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate_raw");

                    b.Property<string>("PlateNorm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate_norm");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint")
                        .HasColumnName("direction");

                    b.Property<string>("JpegPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("jpeg_path");

                    b.Property<short?>("Confidence")
                        .HasColumnType("smallint")
                        .HasColumnName("confidence");

                    b.Property<long?>("CameraId")
                        .HasColumnType("bigint")
                        .HasColumnName("camera_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("PlateNorm");

                    b.HasIndex("CameraId")
                        .HasDatabaseName("ix_passages_camera");

                    b.ToTable("passages", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PaymentRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<long?>("PlaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("place_id");

                    b.Property<long?>("ContractServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_service_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<long?>("ShiftId")
                        .HasColumnType("bigint")
                        .HasColumnName("shift_id");

                    b.Property<string>("ReceiptNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("receipt_no");

                    b.Property<DateTimeOffset?>("CoveredFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("covered_from");

                    b.Property<DateTimeOffset?>("CoveredTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("covered_to");

                    b.Property<string>("EvidenceRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("evidence_ref");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_payments_contract");

                    b.HasIndex("PaidAt")
                        .HasDatabaseName("ix_payments_paidat");

                    b.HasIndex("ContractId", "PlaceId")
                        .HasDatabaseName("ix_payments_contract_place");

                    b.HasIndex("ContractServiceId")
                        .HasDatabaseName("ix_payments_contract_service");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_payments_shift");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PlaceRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PlaceNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("place_no");

                    b.Property<long?>("PlaceTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("place_type_id");

                    b.Property<string>("Block")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("block");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("PlaceNo")
                        .IsUnique()
                        .HasDatabaseName("ux_places_placeno");

                    b.HasIndex("PlaceTypeId")
                        .HasDatabaseName("ix_places_place_type");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PlaceTypeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_place_types_code");

                    b.ToTable("place_types", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PlaceTypeTariffRow", b =>
                {
                    b.Property<long>("PlaceTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("place_type_id");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<bool>("IsDefault")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.HasKey("PlaceTypeId", "TariffId");

                    b.ToTable("place_type_tariffs", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.RoleRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ServiceTypeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_service_types_code");

                    b.ToTable("service_types", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ShiftRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<decimal>("OpeningCash")
                        .HasPrecision(12, 2)
                        .HasDefaultValue(0)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("opening_cash");

                    b.Property<decimal?>("ClosingCash")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("closing_cash");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "StartedAt")
                        .HasDatabaseName("ix_shifts_employee_started");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.TariffRateRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost");

                    b.HasKey("Id");

                    b.HasIndex("TariffId", "ValidFrom", "ValidTo")
                        .HasDatabaseName("ix_tariff_rates_period");

                    b.ToTable("tariff_rates", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.TariffRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("BillingModel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("billing_model");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasDefaultValue("PREPAID")
                        .HasColumnType("character varying(16)")
                        .HasColumnName("payment_mode");

                    b.Property<int>("GracePeriodDays")
                        .HasDefaultValue(20)
                        .HasColumnType("integer")
                        .HasColumnName("grace_period_days");

                    b.Property<string>("OperatorMessage")
                        .HasColumnType("text")
                        .HasColumnName("operator_message");

                    b.Property<string>("StampText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stamp_text");

                    b.Property<string>("StampColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("stamp_color");

                    b.Property<bool>("CanPause")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("can_pause");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("BillingModel")
                        .HasDatabaseName("ix_tariffs_billingmodel");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.VehicleOwnerRow", b =>
                {
                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<bool>("IsPayer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_payer");

                    b.HasKey("VehicleId", "OwnerId");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vehicle_owners_owner");

                    b.ToTable("vehicle_owners", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.VehicleRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PlateNorm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate_norm");

                    b.Property<string>("PlateRaw")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate_raw");

                    b.Property<string>("Brand")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("brand");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("PlateNorm")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_platenorm");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.WatchlistItemRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PlateNorm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plate_norm");

                    b.Property<long?>("WatchlistTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("watchlist_type_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<bool>("NotifyOnIn")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_in");

                    b.Property<bool>("NotifyOnOut")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_out");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("PlateNorm")
                        .HasDatabaseName("ix_watchlist_plate");

                    b.HasIndex("WatchlistTypeId")
                        .HasDatabaseName("ix_watchlist_type_id");

                    b.ToTable("watchlist", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.WatchlistTypeRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<bool>("AllowUnrestrictedAccess")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("allow_unrestricted_access");

                    b.Property<bool>("UnlimitedStay")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("unlimited_stay");

                    b.Property<string>("OperatorMessage")
                        .HasColumnType("text")
                        .HasColumnName("operator_message");

                    b.Property<string>("StampText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stamp_text");

                    b.Property<string>("StampColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("stamp_color");

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_watchlist_types_code");

                    b.ToTable("watchlist_types", (string)null);
                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.AuditLogRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.EmployeeRow", "Employee")
                        .WithMany("AuditLogEntries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.BarrierCommandRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.BarrierRow", "Barrier")
                        .WithMany("Commands")
                        .HasForeignKey("BarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.EmployeeRow", "Employee")
                        .WithMany("BarrierCommands")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.PassageRow", "Passage")
                        .WithMany()
                        .HasForeignKey("PassageId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.BarrierEventRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.BarrierRow", "Barrier")
                        .WithMany("Events")
                        .HasForeignKey("BarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.BarrierCommandRow", "BarrierCommand")
                        .WithMany("Events")
                        .HasForeignKey("BarrierCommandId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraEventRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.CameraRow", "Camera")
                        .WithMany("CameraEvents")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.CameraZoneRow", "CameraZone")
                        .WithMany("CameraEvents")
                        .HasForeignKey("CameraZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.CameraTypeRow", "CameraType")
                        .WithMany("Cameras")
                        .HasForeignKey("CameraTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraZonePlaceRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.CameraZoneRow", "CameraZone")
                        .WithMany("CameraZonePlaces")
                        .HasForeignKey("CameraZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.PlaceRow", "Place")
                        .WithMany("CameraZonePlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.CameraZoneRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.CameraRow", "Camera")
                        .WithMany("CameraZones")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractPlaceRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "Contract")
                        .WithMany("ContractPlaces")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.PlaceRow", "Place")
                        .WithMany("ContractPlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.TariffRow", "Tariff")
                        .WithMany("ContractPlaces")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "LinkedContract")
                        .WithMany("LinkedPlaces")
                        .HasForeignKey("LinkedContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.OwnerRow", "CustomerOwner")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractServiceRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "Contract")
                        .WithMany("ContractServices")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ServiceTypeRow", "ServiceType")
                        .WithMany("ContractServices")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.TariffRow", "Tariff")
                        .WithMany("ContractServices")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ContractVehicleRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "Contract")
                        .WithMany("ContractVehicles")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.VehicleRow", "Vehicle")
                        .WithMany("ContractVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.EmployeeRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.RoleRow", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.NotificationRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.OwnerRow", "Owner")
                        .WithMany("Notifications")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.VehicleRow", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.PassageRow", "Passage")
                        .WithMany()
                        .HasForeignKey("PassageId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PassageRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.CameraRow", "Camera")
                        .WithMany("Passages")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PaymentRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractRow", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractPlaceRow", "ContractPlace")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId", "PlaceId")
                        .HasPrincipalKey("ContractId", "PlaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ContractServiceRow", "ContractService")
                        .WithMany("Payments")
                        .HasForeignKey("ContractServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.EmployeeRow", "Employee")
                        .WithMany("Payments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.ShiftRow", "Shift")
                        .WithMany("Payments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PlaceRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.PlaceTypeRow", "PlaceType")
                        .WithMany("Places")
                        .HasForeignKey("PlaceTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.PlaceTypeTariffRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.PlaceTypeRow", "PlaceType")
                        .WithMany("PlaceTypeTariffs")
                        .HasForeignKey("PlaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.TariffRow", "Tariff")
                        .WithMany("PlaceTypeTariffs")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.ShiftRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.EmployeeRow", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.TariffRateRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.TariffRow", "Tariff")
                        .WithMany("Rates")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.VehicleOwnerRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.VehicleRow", "Vehicle")
                        .WithMany("VehicleOwners")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Infrastructure.Persistence.Entities.OwnerRow", "Owner")
                        .WithMany("VehicleOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                });

            modelBuilder.Entity("Parking.Infrastructure.Persistence.Entities.WatchlistItemRow", b =>
                {
                    b.HasOne("Parking.Infrastructure.Persistence.Entities.WatchlistTypeRow", "WatchlistType")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("WatchlistTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                });

#pragma warning restore 612, 618
        }
    }
}